// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp5.Models;

public partial class Driver
{
    public int ID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string middlename { get; set; }

    public string PassportSerial { get; set; }

    public string PassportNumber { get; set; }

    public string PostCode { get; set; }

    public string Address { get; set; }

    public string AddressLife_ { get; set; }

    public string Company { get; set; }

    public string JobName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string PhotoDescription { get; set; }
}